# Docker Compose for CI/CD Testing
version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: sora2user
      POSTGRES_PASSWORD: sora2pass
      POSTGRES_DB: sora2_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sora2user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - NODE_ENV=test
      - DATABASE_URL=postgresql://sora2user:sora2pass@postgres:5432/sora2_test
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=test-jwt-secret
    ports:
      - "3101:3101"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: Dockerfile.web
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:3101
    ports:
      - "3100:3100"
    depends_on:
      - api
